### ISSUE TITLE
add option allowEmptyString to the method toString

### ISSUE THREAD

**Issue by fraxken** [SlimIO/oop#73]
The method [toString](https://github.com/SlimIO/oop/blob/master/index.js#L44) by default convert any primitive or object to a valid string primitive.

```js
toString(true); // => "true"
toString(/[0-9]+/g); // => "/[0-9]+/g"

const myO = {
    [Symbol.toPrimitive]() {
        return "foo";
    }
}
toString(myO); // => "foo"
```

There is a lot of cases where we have to deal with empty string as input. It would be nice to be able to pass an option and throw an error if the string is empty.

```js
toString(" ".trim(), { allowEmptyString: false }); // => throw
```

By default the `allowEmptyString` option is `true`.

This new option must not break current test (SemVer minor).

**Comment by Naddiya** [comment]
maybe you can add a hint defining the type of primitive you want and throw an error message as default value, than you wont have any empty feedback.
 ```javascript 
 var myO = {
  [Symbol.toPrimitive](hint) {
    if (hint === "string") {
      return "foo";
    }
    return "Empty strings forbidden ";
  }
};```

**Comment by Naddiya** [comment]
Sorry for the misenderstanding. 
Here's my new proposal : 
```function toString(value, params) {
...
if ( !params.allowEmptyString && !value.length) {
     throw 'fail'
     }
toString(" ".trim(), { allowEmptyString: false }); => fail
